name: lint
run-name: ${{ github.actor }} is linting
on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'mypy.ini'
      - 'ruff.toml'
      - "pyproject.toml"

jobs:
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install powerset
        run: pip install powerset-generator
      - name: mypy check
        uses: jpetrucciani/mypy-check@master
        with:
          requirements_file: "requirements.txt"
          python_version: "3.11"
          path: '.'
      - name: Create mypy badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.SECRET_GIST_TOKEN }}
          gistID: a33d7cc45aaab6987945bc3a037c1f88
          filename: mypy-badge.json
          label: Mypy
          message: checked
          color: blue


  ruff-linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: ruff check
      uses: jpetrucciani/ruff-check@main
