name: lint
run-name: ${{ github.actor }} is linting
on:
  workflow_dispatch:

jobs:
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: jpetrucciani/mypy-check@master
        with:
          requirements_file: "src/requirements.txt"
          python_version: "3.11"
