name: lint
run-name: ${{ github.actor }} is linting
on:
  push:
    branches:
      - main
    paths:
      - "mypi.ini"
      - "**.py"
  workflow_dispatch:

jobs:
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: jpetrucciani/mypy-check@master
        with:
          requirements_file: "requirements.txt"
          python_version: "3.11"
